### PR TITLE
update branch 

### PR DESCRIPTION
**Pull request by causefx**
Updating branch as I will be changing the default branch soon.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by homerr** [comment]
Hi @causefx - we can do something better than this depending on how you plan to move forward with dev of Organizr. If you are able to tag your releases on GitHub (v2.0.0, v2.0.1 etc) we can have our build environment pick up on this and trigger builds as you tag new releases (it won't build on pre-release tags). This is also part of our multi-arch image plans as well so users would only need to pull linuxserver/organizr no matter the platform. 

If you give us a nod here when v2.0 is out, I will have got the environment ready for this and can move it over. This is all presuming this is in prep for v2.0! 

Cheers

**Comment by causefx** [comment]
I may look into doing that again as i moved away from it and use a json file now.  I will also be changing the default branch soon, so not sure what would happen with current installs.

**Comment by homerr** [comment]
Hi @causefx I'm just working on migrating this to pipeline building, can you let me know what areas need to be persisted so we can move the app out of /config mount? Things such as upload areas/database files that sort of thing, we can symlink to /config leaving the actual application residing within the container. 

Once Organizr is on pipeline it'll rebuild whenever you commit to v1-master, or, when the packages in the container are updated.

**Comment by causefx** [comment]
the only thing that needs to persisted is the db path which will include the db file and the config folder.

**Comment by homerr** [comment]
Thanks for that. Am working on this more later, writing a little script to move the app out of /config but copy user data. Just a couple of bits left to fix, then final preparation for pipeline building.

https://github.com/linuxserver/docker-organizr/tree/pipeline

**Comment by homerr** [comment]
Finished and should be good to go but does need testing. If you use our image, and wouldn't mind testing with existing data, recreate the container from lsiodev/organizr and let me know how you get on. Should move all user data across, and then serve from /var/www/html with config/db kept in /config/organizr

**Comment by causefx** [comment]
everything looks good! :) 👍

**Comment by thelamer** [comment]
Sorry for the delay, but we no longer install post run, so this pull is no longer valid. 

Thank you for the work on it though, it was needed to know where to grab from when we set this up in the new build system.

**Pull request closed without merging**
